ballmillautomation/urls.py
# django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import TemplateView # new
from devicedata.views import products, about_us, contact_us, terms_and_conditions

urlpatterns = [
    path("admin/", admin.site.urls),

    path("accounts/", include("accounts.urls")), # new
    path("accounts/", include("django.contrib.auth.urls")), # new

    path("", TemplateView.as_view(template_name="home.html"), name="home"), # new
    path('about-us/', about_us, name='about_us'),
    path('contact-us/', contact_us, name='contact_us'),
    path('products/', products, name='products'),
    path('terms-and-conditions/', terms_and_conditions, name='terms_and_conditions'),

    path("blog/", include("blog.urls")), # new , namespace='blog'
    path('devicedata/', include('devicedata.urls')),#new
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView #, post_list, post_detail, PostListView

# app_name = 'blog'

urlpatterns = [
    path("", BlogListView.as_view(), name="blog"),
    path("post/<slug>/", BlogDetailView.as_view(), name="post_detail"), # new
]

blog/models.py
# blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name
    
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)

    body = models.TextField()
    image = models.ImageField(upload_to='', blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now= True)
    status = models.CharField(max_length=2,choices=Status.choices,default=Status.DRAFT)
    
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:details", args=[self.slug,self.publish.year,self.publish.month,self.publish.day])

blog/views.py
# blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post

class BlogListView(ListView):
    model = Post
    template_name = "blog.html"

class BlogDetailView(DetailView): # new
    model = Post
    template_name = "post_detail.html"

templates/about_us.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-12" style="padding: 5%;">
    <h1>About Us</h1>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
      <div class="col-md-12 p-lg-5 mx-auto my-12">
        <h1 class="display-4 fw-normal">A few words about us & our work</h1>
        <p class="lead fw-normal">We are a leading solutions provider for ball mill automation. Our mission is to improve the efficiency and productivity of the ball mill process through innovative technology and high-quality services. Our team of experts is dedicated to providing the best solutions for our clients, ensuring that their operations run smoothly and effectively. </p>
        <a class="btn btn-outline-success" href="{% url 'contact_us' %}">Contact Us to Know more</a>
      </div>
      <div class="product-device shadow-sm d-none d-md-block"></div>
      <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</div>
{% endblock %}

templates/base.html
<!-- templates/base.html -->
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <!-- <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">-->
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.css" rel="stylesheet"/>     -->
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">    
    <title>Ball Mill Automation!</title>

    </head>
    <body>
        <!-- ======= Top Bar ======= -->
        <section id="topbar" class="d-flex align-items-center">
            <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope-fill"></i><a href="mailto:contact@example.com">info@example.com</a>
                <i class="bi bi-phone-fill phone-icon"></i> +1 5589 55488 55
            </div>
            <div class="social-links d-none d-md-block">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
            </div>
        </section>
        <header>

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                <div class="container">
                    <a class="navbar-brand" style="color: white;" href="{% url 'home' %}">Ball Mill Automation</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" style="background-color: #757575;">
                        <div class="offcanvas-header" style="background-color: white;">
                            <h5 class="offcanvas-title">Menu</h5>
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="{% url 'blog' %}">Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="{% url 'products' %}">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="{% url 'about_us' %}">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="{% url 'contact_us' %}">Contact Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="{% url 'terms_and_conditions' %}">T&C</a>
                                </li>
                                {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link" style="color: white;" href="{% url 'dashboard' user.pk %}">Dashboard</a>
                                    </li>
                                {% endif %}
                            </ul>
                            {% if user.is_authenticated %}
                                <div class="dropdown mt-3">
                                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false" style="color:white; " >
                                        {{ user.username }}
                                    </a>
                                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                                        <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                                    </ul>
                                </div>
                            {% else %}
                            <div class="d-flex mt-3">
                                <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
                                <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        </header>
        <div class="container-fluid" >
            <main>
                {% block content %}
                {% endblock content %}
            </main>
        </div>            

        <!-- Optional JavaScript; choose one of the two! -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <!-- MDB -->
        <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.js" ></script> -->
    </body>
</html>

templates/company_dashboard.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ company.name }}</h1>
  {% if devices %}
    <table>
      <thead>
        <tr>
          <th>Device Name</th>
          <th>Last Data</th>
          <th>Detail</th>
        </tr>
      </thead>
      <tbody>
        {% for device in devices %}
          <tr>
            <td>{{ device.name }}</td>
            {% if device.last_data %}
              <td>{{ device.last_data.data }}</td>
            {% else %}
              <td>No Data Found</td>
            {% endif %}
            <td><a href="{% url 'device_detail' company_id=device.company.pk pk=device.pk %}">View Detail</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No Devices Found</p>
  {% endif %}
{% endblock %}

templates/company_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ company.name }}</h1>
  {% if devices %}
    <h2>Devices</h2>
    <ul>
      {% for device in devices %}
        {% comment %} <li><a href="{% url 'device_detail' company_pk=company.pk pk</span>=device.pk %}">{{ device.name }}</a></li> {% endcomment %}
        <li><a href="">{{ device.name }}w</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>This company doesn't have any devices yet.</p>
  {% endif %}
{% endblock %}

templates/contact_us.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-12" style="padding: 5%;">
    <h1>Contact Us</h1>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
      <div class="col-md-12 p-lg-5 mx-auto my-12">
        <h1 class="display-4 fw-normal">A few words about us & our work</h1>
        <p class="lead fw-normal">If you have any questions or need assistance, please feel free to contact us using the information below: </p>
        <div class="list-group">
          <a href="mailto:ballmillautomation@gmail.com" class="list-group-item list-group-item-action">
            <i class="bi bi-envelope-fill me-2"></i>Email: ballmillautomation@gmail.com
          </a>
          <a href="tel:+919975728991" class="list-group-item list-group-item-action">
            <i class="bi bi-telephone-fill me-2"></i>Phone: +91-9975728991
          </a>
          <a class="list-group-item list-group-item-action">
            <i class="bi bi-geo-fill me-2"></i>Address: Jaipur, Rajasthan, India
          </a>
        </div>
        
        {% if user.is_anonymous %}
          <a class="btn btn-outline-success" href="{% url 'signup' %}" style="margin: 3em;">Sign Up Today</a>
        {% endif %}
      </div>
      <div class="product-device shadow-sm d-none d-md-block"></div>
      <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</div>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% comment %} {% load templatetags %}
{% load division_filters %} {% endcomment %}
{% load static %}

<script src="{% static 'dashboard_auto_reload.js' %}"></script>
{% block content %}

<div class="container-fluid bg-dark text-white" style="padding: 30px;">
  {% if company_devices_data %}
    <div class="row">
      {% for company_data in company_devices_data %}
        <div class="col">
          <div class="p-3" style="background-color: darkslategray;">
            <h2 class="text-center text-white">{{ company_data.company.name }}</h2>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      {% for company_data in company_devices_data %}
        {% for device_data in company_data.devices_data %}
          <div class="col">
            <div class="bg-light p-3">
              <div class="text-center text-black">
                <span style="color: green;"><i class="fas fa-2x fa-microchip"></i></span>
                <h3>{{ device_data.device.name }}</h3><hr>
                <!-- <p>
                  <span style="font-weight: 600; text-align: left;">Total Bag (00:00 To 24:00 ):</span> <span style="font-weight: 900; color: rgb(60, 116, 7); text-align: right;"> {{ device_data.total_bags }}</span><br>
                  <span style="font-weight: 600; text-align: left;">Average Time: {{ device_data.average_time|floatformat:2 }} seconds</span><br>
                  <span style="font-weight: 600;">Average of Bags: {{ device_data.average_only|floatformat:2 }}</span><br>
                  <span style="font-weight: 600;">MorningShift ({{ company_data.company.morning_shift_start_time }} To {{ company_data.company.evening_shift_start_time }}) Bags: {{ device_data.morning_shift}} </span><br>
                  <span style="font-weight: 600;">EveningShift ({{ company_data.company.evening_shift_start_time }} To {{ company_data.company.morning_shift_start_time }}) Bags:   {{ device_data.evening_shift}} </span><br>
                </p> -->
                <table style="border: none; width: 100%;">
                  <tr>
                    <td><span style="font-weight: 600;">Today's Bag <sapn style="font-weight: 100;">(00:00 To 24:00)</sapn>:</span></td>
                    <td><span style="font-weight: 900; color: rgb(60, 116, 7);">{{ device_data.total_bags }}</span></td>
                  </tr>
                  <tr>
                    <td><span style="font-weight: 600;">Average Time <sapn style="font-weight: 100;">(in seconds)</sapn>:</span></td>
                    <td><span style="font-weight: 900; color: rgb(60, 116, 7);">{{ device_data.average_time|floatformat:2 }} </span></td>
                  </tr>
                  <tr>
                    <td><span style="font-weight: 600;">Average of Bags :</span></td>
                    <td><span style="font-weight: 900; color: rgb(60, 116, 7);">{{ device_data.average_only|floatformat:2 }}</span></td>
                  </tr>
                  <tr>
                    <td><span style="font-weight: 600;">MorningShift <sapn style="font-weight: 100;">({{ company_data.company.morning_shift_start_time }} To {{ company_data.company.evening_shift_start_time }})</sapn> Bags:</span></td>
                    <td><span style="font-weight: 900; color: rgb(60, 116, 7);">{{ device_data.morning_shift}}</span></td>
                  </tr>
                  <tr>
                    <td><span style="font-weight: 600;">EveningShift <sapn style="font-weight: 100;">({{ company_data.company.evening_shift_start_time }} To {{ company_data.company.morning_shift_start_time }})</sapn> Bags:</span></td>
                    <td><span style="font-weight: 900; color: rgb(60, 116, 7);">{{ device_data.evening_shift}}</span></td>
                  </tr>
                </table>
                <!-- <h4>Average of last:<br>L5 = {{avg_L5|floatformat:2 }}<br>L10 = {{avg_L10|floatformat:2 }}<br>L15 = {{avg_L15|floatformat:2 }}<br>L20 = {{avg_L20|floatformat:2 }}<br></h4> -->
                <a href="{% url 'device_detail' company_id=company_data.company.pk pk=device_data.device.pk %}" class="btn btn-primary">Check Details</a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endfor %}
    </div>
  {% else %}
    <p>You don't have any companies yet.</p>
  {% endif %}
</div>

{% endblock %}

templates/details.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|linebreaks }}
{% endblock %}

templates/device_detail.html
{% extends 'base.html' %}
{% load templatetags %}
{% load static %}

{% block content %}
<div class="container my-4" style="background-color:#37474F; padding-top:3%">
  <h1 class="mb-4" style="color:whitesmoke">{{ object.name }}</h1>
  <div class="row">
    <div class="col-md-6">
      <div class="p-4 rounded mb-4" style="background-color:#E0F7FA;">
        <h3>Total Bags Today</h3>
        <p class="fs-3">{{ total_bags }}</p>
        <h3>Average Time Today</h3>
        <p class="fs-3">{{ average_time|floatformat:2 }} seconds</p>
        <h3>Average Bag/Hour</h3>
        <p class="fs-3">{{ average_per_hour|floatformat:2 }}</p>
        <h3>Predicted Bags Today</h3>
        <p class="fs-3">{{ predicted_bags_today }}</p><hr>
        <h4>Average of last:<br>L5 = {{avg_L5|floatformat:2 }}<br>L10 = {{avg_L10|floatformat:2 }}<br>L15 = {{avg_L15|floatformat:2 }}<br>L20 = {{avg_L20|floatformat:2 }}<br></h4>
        <!-- <h3>Feed Status</h3>
        <p class="fs-3">{{ milldata_today.feed_status }}</p>
        <h3>Overload Status</h3>
        <p class="fs-3">{{ milldata_today.overload_status }}</p> -->
      </div>
    </div>
    <div class="col-md-6">
      <!-- Link to other Devices -->
      <div class="bg-light p-4 rounded mb-4">
        <div>
          <h3>Feed Status</h3>
          <p class="fs-3" style="color:{{ milldata_today.feed_status|yesno:'red,green' }}">{{ milldata_today.feed_status|yesno:'ON,OFF' }}</p>
          <h3>Overload Status</h3>
          <p class="fs-3" style="color:{{ milldata_today.overload_status|yesno:'red,green' }}">{{ milldata_today.overload_status|yesno:'Yes,No' }}</p>
        </div><hr>
        <div class="d-flex flex-wrap justify-content-start">
          <h3>Switch Device</h3>
          <div>
            {% for company_data in company_devices_data %}
                {% for device_data in company_data.devices_data %}
                    <a href="{% url 'device_detail' company_id=device_data.device.company.pk pk=device_data.device.pk %}" class="btn btn-primary m-2">{{ device_data.device.name }}</a>
                {% endfor %}
            {% endfor %}
          </div>
        </div><hr>
      </div>
    </div>
                  
      <div class="bg-light p-4 rounded mb-4">
        <!-- Show device details and a button to edit feeding parameters -->
        <h2>Device Details</h2>
        <ul class="list-group list-group-flush mb-3">
          {% comment %} <li class="list-group-item">Status: {% if object.is_active %}<span class="badge bg-success">Active</span>{% else %}<span class="badge bg-danger">Inactive</span>{% endif %}</li> {% endcomment %}
          <li class="list-group-item">Status: {% if object.status == 'active' %}<span class="badge bg-success">Active</span>{% else %}<span class="badge bg-danger">Inactive</span>{% endif %}</li>

          <li class="list-group-item">Circle: {{ object.circle }}</li>
          <li class="list-group-item">Feed Time: {{ object.feed_time }}</li>
          <li class="list-group-item">Circle Hold: {{ object.circle_hold }}</li>
          <li class="list-group-item">Actual Hold: {{ object.actual_hold }}</li>
        </ul>
        <button class="btn btn-danger mb-3" onclick="location.href='{% url 'edit_feeding' object.pk %}'">Edit Feeding</button>
      </div>
      <!-- Date range picker form and export options -->
      <div class="bg-light p-4 rounded mb-4">
        <h2>Select Dates to check production data:</h2>
        <form method="GET" action="" class="mb-3">
          <div class="row">
            <div class="col">
              <label for="start_date" class="form-label">Start Date:</label>
              <input type="date" name="start_date" id="start_date" class="form-control" value="{{ start_date }}">
            </div>
            <div class="col">
              <label for="end_date" class="form-label">End Date:</label>
              <input type="date" name="end_date" id="end_date" class="form-control" value="{{ end_date }}">
            </div>
          </div>
          <button type="submit" class="btn btn-primary mt-2">Filter</button>
        </form>
        <button class="btn btn-success mb-3" onclick="location.href='{% url 'export_pdf' object.pk %}'">Export as PDF</button>
        <button class="btn btn-success mb-3" onclick="location.href='{% url 'export_excel' object.pk %}'">Export as Excel</button>
      </div>

    </div>       
  </div>
  <!-- Display Milldata for the selected date range -->
<div class="container my-4" style="padding-top:3%">
  <div class="bg-light p-4 rounded mb-4">
    <h2>Milldata</h2>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Bag No.</th>
          <th>Average</th>
          <th>Fill Time</th>
          <th>Date Time</th>
          <th>Weight</th>
          <!-- <th>Feed Status</th>
          <th>Overload Status</th> -->
        </tr>
      </thead>
      <tbody>
        {% for milldata in milldata_paged %}
          <tr>
            <td>{{ forloop.counter|reverse_katta_number:milldata_paged }}</td>
            <td>{{ milldata.avg_per_hour|floatformat:2 }}</td>
            <td>{{ milldata.fill_time }} </td>
            <td>{{ milldata.katta_time }} </td>
            <td>{{ milldata.katta_weight }} </td>
            <!-- <td>{{ milldata.feed_status }} </td>
            <td>{{ milldata.overload_status }} </td> -->
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  <!-- Pagination -->
  <nav aria-label="Page navigation" class="mb-4">
    <ul class="pagination">
      {% if milldata_paged.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% querystring request page=milldata_paged.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="visually-hidden">Previous</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <span aria-hidden="true">&laquo;</span>
            <span class="visually-hidden">Previous</span>
          </span>
        </li>
      {% endif %}
      {% for i in milldata_paged.paginator.page_range %}
        {% if milldata_paged.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% querystring request page=i %}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if milldata_paged.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% querystring request page=milldata_paged.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="visually-hidden">Next</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <span aria-hidden="true">&raquo;</span>
            <span class="visually-hidden">Next</span>
          </span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}

templates/edit_feeding.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 style="padding-top: 1em;">Edit Feeding Parameters</h1>
    <form method="post" style="padding-bottom: 2em;">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/post_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
        {% endif %}
        <div class="card-header">
            <h2 class="card-title">{{ post.title }}</h2>
            <p class="card-subtitle text-muted">Published {{ post.publish }} by {{ post.author }}</p>
        </div>
        <div class="card-body">
            <p class="card-text">{{ post.body }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/post_list.html
{% extends "blog/base.html" %}
{% block title %}Blogs{% endblock %}
{% block content %}
    <h1 style="margin-top: 2em;">My Blog</h1>
    {% for post in posts %}
        <h2>
            {% comment %} <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a> {% endcomment %}
            {% comment %} <a href="{% url 'details' post.id %}">{{ post.title }}</a> {% endcomment %}
            <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
        </h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

templates/terms_and_conditions.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-12" style="padding: 5%;">
    <!-- <h1>Our Products</h1> -->
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
      <div class="col-md-12 p-lg-5 mx-auto my-12">
        <h1 class="display-4 fw-normal">Terms and Conditions</h1>
        <p class="lead fw-normal">Please read these terms and conditions carefully before using our services. By accessing or using our website and services, you agree to be bound by these terms. If you do not agree with any part of these terms, you must not use our services.</p>
        <!-- <a class="btn btn-outline-success" href="#">Launched & Available</a> -->
      </div>
      <div class="product-device shadow-sm d-none d-md-block"></div>
      <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</div>
{% endblock %}